### ISSUE TITLE
Undocumented layer name assumption

### ISSUE THREAD

**Issue by globalcitizen** [Mambix/co2tools#10]
```
Processing group: main
dxf/test1.dxf
    Source: dxf/test1.dxf
        extrude: 2.0
        Layers: dict_keys([])
Traceback (most recent call last):
  File "/usr/local/bin/co2tools", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/co2tools/__init__.py", line 79, in main
    solidify(yaml_data, execute_action, execute_section, execute_file, base_folder, boolean_engine)
  File "/usr/local/lib/python3.9/site-packages/co2tools/stl/__init__.py", line 44, in solidify
    b.build(modifications, target)
  File "/usr/local/lib/python3.9/site-packages/co2tools/stl/builder.py", line 204, in build
    self.extrude(instructions)
  File "/usr/local/lib/python3.9/site-packages/co2tools/stl/builder.py", line 102, in extrude
    raise BaseException(1, 'Layer {} is not present in DXF file.'.format(self.LAYER_CUT))
BaseException: (1, 'Layer CUT is not present in DXF file.')
```

**Comment by Mambix** [comment]
@globalcitizen can you elaborate a bit what the issue is please.

I assume I need to update some documentation, but what specifically is not clear?

**Comment by globalcitizen** [comment]
It looks like your code is searching for a layer that is not present in the DXF file.

```
BaseException: (1, 'Layer CUT is not present in DXF file.')
```

If this is a requirement, I did not see it documented. Anyway, I am switching to [OpenSCAD](https://openscad.org/) which apparently has DXF import and extrusion as a first-order feature plus loads of other cool features.

**Comment by Mambix** [comment]
Yes, the way it works is you have a `CUT` layer which are outer perimeters and a `HOLES` layer, which as the name suggests, represent the parts that are cut out of CUT layer. You can name the layers how you want as long as you define that names in the yaml file.
